In [3]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

In [5]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

"""
variable list_ is a list data type and 
variable array_list is a numpy.ndarray data type 
because it is converted to a numpy array using np.array() function
"""

type(list_), type(array_list)

(list, numpy.ndarray)

In [11]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

for i in list_:
    print(type(i))
    
for j in array_list:
    print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [12]:
# Q3. Considering the following changes in the variable, array_list:
    
# array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

array_list = np.array(object = list_, dtype = int)

In [20]:
"""
after performing following code the datatype of all the element from string to integer of only array_list

list_ will not be affected from the following code 
"""
for j in list_:
    print(type(j))
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [21]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [22]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

"""
shape give the no. of row and column in the array and size give no. of element present in the array
the code to file shape and size of num_array are as follow
"""
num_array.shape, num_array.size

((2, 3), 6)

In [28]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.

array1 = np.zeros((3,3))
array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

#below code give matrix on the basis of a standard distribution 
array2 = np.random.randn(5,5)

# below code give matrix of shape in between (0,1)
array3 = np.random.rand(5,5)

# below code give metrix with only 1's on the diagonal and all other elements are 0's
array4 = np.diag([1,1,1,1,1])


In [50]:
array4

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])